"use strict";

/** Kode error terstruktur untuk /api/master/* */
module.exports = Object.freeze({
  MASTER_VALIDATION_ERROR: "MASTER_VALIDATION_ERROR",
  MASTER_PARENT_NOT_FOUND: "MASTER_PARENT_NOT_FOUND",
  MASTER_DATASET_MISMATCH: "MASTER_DATASET_MISMATCH",
  MASTER_INTERNAL_ERROR: "MASTER_INTERNAL_ERROR",
  MASTER_HIERARCHY_INVALID: "MASTER_HIERARCHY_INVALID",
});
